import type { GetServerSideProps, Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { Locale, i18n } from "@/i18n.config";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import { getDictionary } from "@/lib/dictionary";
import "@/styles/App.scss";
import FloatingButtons from "@/components/FloatingButtons/FloatingButtons";
import { TranslationProvider } from "@/contexts/TranslationProvider";

export const metadata: Metadata = {
  title: {
    template: "%s | SKM",
    default: "SKM Music Store",
  },
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={ubuntu.className}>
        <TranslationProvider>
          <Header lang={params.lang} />
          <div className="wrapper">{children}</div>
          <Footer lang={params.lang} />
          <FloatingButtons lang={params.lang} />
        </TranslationProvider>
      </body>
    </html>
  );
}
