import type { Metadata } from 'next';
import { Locale, i18n } from '@/i18n.config';
import Header from '../components/Header/Header';

import Footer from '../components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body>
        <header>
          <Header lang={params.lang} />
        </header>
        <main>{children}</main>
        <footer>
          <Footer lang={params.lang} />
        </footer>
      </body>
    </html>
  );
}
